spring:
  application:
    name: rms
  datasource:
    url: jdbc:mysql://localhost:3306/rmsdb
    username: root
    password: jero123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    open-in-view: false



