spring:
  application:
    name: rms
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: root
    password: ${DB_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

